### ISSUE TITLE
[Feature request]: Tuono CLI testing

### ISSUE THREAD

**Issue by KingTheSim** [tuono-labs/tuono#144]
### Is your feature request related to a problem? Please describe.

The tuono_cli currently doesn't have integration tests.

### Describe the solution you'd like

Using the trycmd crate, I've added a testcase for the tuono --help command. The idea is for the test cases to include all possible tuono commands later on.

**Comment by KingTheSim** [comment]
The last commit removes the .vscode folder. .gitignore also will not ignore the folder

**Comment by marcalexiei** [comment]
Done via #177
