### ISSUE TITLE
Update macro namings to avoid collisions

### ISSUE THREAD

**Issue by Valerioageno** [tuono-labs/tuono#186]
Right now, the `tuono_lib::handlers` macro creates to hidden functions
```
pub async fn route() -> ...
pub async fn api() -> ...
```

Since the names are very common, the user might create a function with the same name, breaking then the build.

We should update the names with `tuono__internal__route` and `tuono__internal__api`

**Comment by NayanVR** [comment]
I'd like to contribute

**Comment by Valerioageno** [comment]
Do you have rust knowledge to take this task by your own?

**Comment by NayanVR** [comment]
I need to refactor the name of functions without any conflicts right?

**Comment by Valerioageno** [comment]
Nope. We need to update the macro attributes and to accordingly update the generated `.tuono/main.rs` file (updating then all the tests).

**Comment by mustafasegf** [comment]
hi there, I want to pick up this task
