### ISSUE TITLE
Add documentation website link to crates documentation

### ISSUE THREAD

**Issue by Valerioageno** [tuono-labs/tuono#195]
In order to keep all the documentation in the same place, we won't take care of the `crates` autogenerated documentation.

With this task we add the documentation link in the `tuono`, `tuono_lib` and `tuono_lib_macros` documentation headers.

The prompt should be something like:

```
## Tuono
Tuono is a full-stack web framework for building React applications using Rust as the backend with a strong focus on usability and performance.

You can find the full documentation at tuono.dev
```

## Current state
![Image](https://github.com/user-attachments/assets/5c24aacf-5c37-4320-b936-35548a6133de)

**Comment by mustafasegf** [comment]
let me do this. is it ok to use 
```## Tuono
Tuono is a full-stack web framework for building React applications using Rust as the backend with a strong focus on usability and performance.

You can find the full documentation at tuono.dev
```
prompt directly?

**Comment by Valerioageno** [comment]
That's perfect. Thanks
