### ISSUE TITLE
[Bug]: Using tuono 0.15.0 with @primer/react results in 

### ISSUE THREAD

**Issue by pveierland** [tuono-labs/tuono#204]
### Description

Using tuono with `@primer/react` results in the following panic:

```
<unknown>:566223: Uncaught ReferenceError: HTMLElement is not defined
thread 'tokio-runtime-worker' panicked at /project/.direnv/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tuono_lib-0.15.0/src/ssr.rs:54:10:
called `Result::unwrap()` on an `Err` value: InvalidJs("Execute your script with d8 to debug")
stack backtrace:
   0:     0x55fd87ba432a - std::backtrace_rs::backtrace::libunwind::trace::h27221650d798474c
                               at /rustc/dff3e7ccd4a18958c938136c4ccdc853fcc86194/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x55fd87ba432a - std::backtrace_rs::backtrace::trace_unsynchronized::h8771451707617db7
                               at /rustc/dff3e7ccd4a18958c938136c4ccdc853fcc86194/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55fd87ba432a - std::sys::backtrace::_print_fmt::h7b49bd1e8800c0c6
                               at /rustc/dff3e7ccd4a18958c938136c4ccdc853fcc86194/library/std/src/sys/backtrace.rs:66:9
   3:     0x55fd87ba432a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h95a44616294b6072
                               at /rustc/dff3e7ccd4a18958c938136c4ccdc853fcc86194/library/std/src/sys/backtrace.rs:39:26
   4:     0x55fd87bd1963 - core::fmt::rt::Argument::fmt::h56f0695bc3b47563
```

### Expected behaviour

It it expected that it should be possible to render components without panic, and in an SSR context as this is possible through Next.js.

### How to reproduce

See: https://primer.style/guides/react

1. Install dependencies in addition to tuono: `npm install @primer/react react react-dom styled-components`.

2. Create `src/routes/__root.tsx`:

```
import type { ReactNode, JSX } from "react";
import { Button, BaseStyles, ThemeProvider } from "@primer/react";

interface RootRouteProps {
	children: ReactNode;
}

export default function RootRoute({ children }: RootRouteProps): JSX.Element {
	return (
		<ThemeProvider>
			<BaseStyles>
				<Button>Click me</Button>
			</BaseStyles>
		</ThemeProvider>
	);
}
```

3. Run `tuono dev`

4. Load route and see error as shown in bug description.

### Tuono version

0.15.0

### OS

NixOS

### Browser

Firefox

### Node version

v20.17.0

### Rust version

rustc 1.85.0-nightly (dff3e7ccd 2024-11-26)

### Crate version

0.15.0

### Node Package Manger version

Yarn 1.22.22

**Comment by Valerioageno** [comment]
So the problem is because the [live-region-element](https://github.com/primer/live-region-element) package that is used within `@primer/react`.
Luckily, very few components are impacted by this library (see [here the list](https://github.com/search?q=repo%3Aprimer%2Freact%20live-region-element&type=code)).
We need to find a way to strip it away from the server build either way, but for now only the Announce and Button components cannot be used.

> Note: I saw that styled-component on tuono are not supported yet on the Server side. I'll log a task for better supporting them on the server as well

**Comment by Valerioageno** [comment]
Logged here: https://github.com/orgs/tuono-labs/projects/2?pane=issue&itemId=90079111

**Comment by Valerioageno** [comment]
For the polyfill part @marcalexiei just fixed it. With `tuono v0.16.0` you can define custom plugins in the `tuono.config.ts`.

In your specific case, you need to install `@rollup/plugin-inject` (needed for injecting the polyfills) and `@lit-labs/ssr-dom-shim` (the polyfill library).

```ts
import type { TuonoConfig } from "tuono/config";
import inject from "@rollup/plugin-inject";

const config: TuonoConfig = {
  vite: {
    plugins: [
      {
        enforce: "post",
        ...inject({
          HTMLElement: ["@lit-labs/ssr-dom-shim", "HTMLElement"],
          customElements: ["@lit-labs/ssr-dom-shim", "customElements"],
        }),
      },
    ],
  },
};

export default config;
```
The ssr styled-component thing is still not supported but it will be addressed separately.
