### ISSUE TITLE
[Bug]: Catch-all paths has double underscore causing build warning

### ISSUE THREAD

**Issue by pveierland** [tuono-labs/tuono#226]
### Description

The new catch-all path feature uses double underscores which triggered build warnings:

```
warning: module my_prefix__catch_all_inner_hyphen_store_hyphen_path should have a snake case name
  --> crates/project/.tuono/main.rs:15:25
   |
15 |                     mod my_prefix__catch_all_inner_hyphen_store_hyphen_path;
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: convert the identifier to snake case: nix_store_dyn_catch_all_inner_hyphen_store_hyphen_path
```

### Expected behaviour

No build warning.

### How to reproduce

Create `[...catch_all].{rs,tsx}` route.

Tuono version 0.16.3 (web) + 0.16.2 (CLI).

**Comment by mustafasegf** [comment]
one workaround i can think of is to add `.replace("__", "_")` at the end of https://github.com/tuono-labs/tuono/blob/main/crates/tuono/src/route.rs#L56. if you ok with that I can make a pr for it
