### ISSUE TITLE
Filter by tag `tuono new` command template download

### ISSUE THREAD

**Issue by Valerioageno** [tuono-labs/tuono#231]
Right now, the `tuono new` command always downloads the latest templates available within the `examples/` folder. This creates a mismatch caused by breaking changes between older CLI versions with new examples setups.

Since the CLI version always matches the release names, we could prevent this situation by requesting the templates related to a specific release.

**Comment by gravitypowerful** [comment]
I will solve this issue.

**Comment by gravitypowerful** [comment]
I made PR [#261](https://github.com/tuono-labs/tuono/pull/261).
